---
title: "Handling Categorical Variables"
output: html_document
---

```{r}
library(lsa)
library(splitstackshape)
workdir <- '/home/Shalini/Desktop/SEM 5/DA/Project/Datasets/'
setwd(workdir)
df <- read.csv('bgg_db_2018_01.csv')
```

Splitting Mechanic and Categorical Variables to dummy Variables
```{r}
catSplit <- cSplit(df, "category", ",")
catSplitDummy <- df
for (i in 1:nrow(catSplit)){
  for(j in 21:27){
    if(!is.na(catSplit[i,as.numeric(j)]))
    {
      cat <- as.character(catSplit[[i,as.numeric(j)]])
      cat_col <- paste("catSplit", cat, sep = "_")
      catSplitDummy[i, cat_col]<-1
    }
  }
}

catSplitDummy$catSplit_NA <- NULL
catSplitDummy[is.na(catSplitDummy)] <- 0

mechSplit1 <- cSplit(df, "mechanic", ",")

mechSplitDummy <- df
for (i in 1:nrow(mechSplit1)){
  for(j in 21:27){
    if(!is.na(mechSplit1[i,as.numeric(j)]))
    {
      mech <- as.character(mechSplit1[[i,as.numeric(j)]])
      mech_col <- paste("mechSplit", mech, sep = "_")
      mechSplitDummy[i, mech_col]<-1
    }
  }
}
mechSplitDummy$mechSplit_NA <- NULL
mechSplitDummy[is.na(mechSplitDummy)] <- 0
DummyDataFrame <- merge(catSplitDummy, mechSplitDummy, by = colnames(df))
```

DummyDataFrame contains dummy variables for categorical and mechanic data and this code can be used for other analyses on different data frames. 
```{r}
View(DummyDataFrame)
```
